<?php

acf_add_local_field_group([
    'key'    => 'group_colors',
    'title'  => 'Branding & Colors',
    'fields' => [
        [
            'key'           => 'field_color_primary',
            'label'         => 'Primary Color',
            'name'          => 'color_primary',
            'type'          => 'color_picker',
            'default_value' => '#165783',
            'instructions'  => 'Main brand color — used for header background, headings.',
        ],
        [
            'key'           => 'field_color_secondary',
            'label'         => 'Secondary Color',
            'name'          => 'color_secondary',
            'type'          => 'color_picker',
            'default_value' => '#004c7a',
            'instructions'  => 'Supporting color — backgrounds, cards.',
        ],
        [
            'key'           => 'field_color_accent',
            'label'         => 'Accent Color',
            'name'          => 'color_accent',
            'type'          => 'color_picker',
            'default_value' => '#1face3',
            'instructions'  => 'Highlight color — badges, sale tags, icons.',
        ],
        [
            'key'           => 'field_color_text',
            'label'         => 'Text Color',
            'name'          => 'color_text',
            'type'          => 'color_picker',
            'default_value' => '#41474f',
            'instructions'  => 'Default body text color used across the site.',
        ],
        [
            'key'           => 'field_color_heading',
            'label'         => 'Heading Text',
            'name'          => 'color_heading',
            'type'          => 'color_picker',
            'default_value' => '#191c1d',
            'instructions'  => 'Main dark text color used for titles, labels, and totals.',
        ],
        [
            'key'           => 'field_color_muted',
            'label'         => 'Muted Text',
            'name'          => 'color_muted',
            'type'          => 'color_picker',
            'default_value' => '#777777',
            'instructions'  => 'Secondary text color used for meta text and helper labels.',
        ],
        [
            'key'           => 'field_color_btn_bg',
            'label'         => 'Button Background',
            'name'          => 'color_btn_bg',
            'type'          => 'color_picker',
            'default_value' => '#165783',
        ],
        [
            'key'           => 'field_color_btn_text',
            'label'         => 'Button Text',
            'name'          => 'color_btn_text',
            'type'          => 'color_picker',
            'default_value' => '#ffffff',
        ],
    ],
    'location' => [[['param' => 'options_page', 'operator' => '==', 'value' => 'theme-colors']]],
]);
