<?php

acf_add_local_field_group([
    'key'    => 'group_company',
    'title'  => 'Company Info',
    'fields' => [
        [
            'key'   => 'field_company_name',
            'label' => 'Company Name',
            'name'  => 'company_name',
            'type'  => 'text',
        ],
        [
            'key'   => 'field_company_tagline',
            'label' => 'Tagline / Slogan',
            'name'  => 'company_tagline',
            'type'  => 'text',
        ],
        [
            'key'           => 'field_company_logo_light',
            'label'         => 'Logo (Light — for dark backgrounds)',
            'name'          => 'company_logo_light',
            'type'          => 'image',
            'return_format' => 'array',
            'preview_size'  => 'medium',
        ],
        [
            'key'           => 'field_company_logo_dark',
            'label'         => 'Logo (Dark — for light backgrounds)',
            'name'          => 'company_logo_dark',
            'type'          => 'image',
            'return_format' => 'array',
            'preview_size'  => 'medium',
        ],
        [
            'key'   => 'field_company_address',
            'label' => 'Address',
            'name'  => 'company_address',
            'type'  => 'textarea',
            'rows'  => 3,
        ],
        [
            'key'        => 'field_company_phones',
            'label'      => 'Phone Numbers',
            'name'       => 'company_phones',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 5,
            'layout'     => 'table',
            'button_label' => 'Add Phone',
            'sub_fields' => [
                [
                    'key'   => 'field_phone_label',
                    'label' => 'Label',
                    'name'  => 'phone_label',
                    'type'  => 'text',
                    'placeholder' => 'e.g. Main, Support',
                    'wrapper' => ['width' => '30'],
                ],
                [
                    'key'   => 'field_phone_number',
                    'label' => 'Number',
                    'name'  => 'phone_number',
                    'type'  => 'text',
                    'placeholder' => '+1 234 567 890',
                    'wrapper' => ['width' => '70'],
                ],
            ],
        ],
        [
            'key'        => 'field_company_emails',
            'label'      => 'Email Addresses',
            'name'       => 'company_emails',
            'type'       => 'repeater',
            'min'        => 0,
            'max'        => 5,
            'layout'     => 'table',
            'button_label' => 'Add Email',
            'sub_fields' => [
                [
                    'key'   => 'field_email_label',
                    'label' => 'Label',
                    'name'  => 'email_label',
                    'type'  => 'text',
                    'placeholder' => 'e.g. Sales, Support',
                    'wrapper' => ['width' => '30'],
                ],
                [
                    'key'   => 'field_email_address',
                    'label' => 'Email',
                    'name'  => 'email_address',
                    'type'  => 'email',
                    'wrapper' => ['width' => '70'],
                ],
            ],
        ],
        [
            'key'        => 'field_company_hours',
            'label'      => 'Business Hours',
            'name'       => 'company_hours',
            'type'       => 'repeater',
            'layout'     => 'table',
            'button_label' => 'Add Row',
            'sub_fields' => [
                [
                    'key'     => 'field_hours_day',
                    'label'   => 'Day(s)',
                    'name'    => 'hours_day',
                    'type'    => 'text',
                    'placeholder' => 'Mon – Fri',
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key'     => 'field_hours_time',
                    'label'   => 'Hours',
                    'name'    => 'hours_time',
                    'type'    => 'text',
                    'placeholder' => '09:00 – 18:00',
                    'wrapper' => ['width' => '50'],
                ],
            ],
        ],
        [
            'key'   => 'field_company_vat',
            'label' => 'VAT Number',
            'name'  => 'company_vat',
            'type'  => 'text',
        ],
        [
            'key'   => 'field_company_registration',
            'label' => 'Registration Number',
            'name'  => 'company_registration',
            'type'  => 'text',
        ],
    ],
    'location' => [[['param' => 'options_page', 'operator' => '==', 'value' => 'theme-company']]],
]);
