<?php

acf_add_local_field_group([
    'key'    => 'group_company',
    'title'  => 'Company Info',
    'fields' => [
        [
            'key'   => 'field_company_name',
            'label' => 'Company Name',
            'name'  => 'company_name',
            'type'  => 'text',
        ],
        [
            'key'   => 'field_company_tagline',
            'label' => 'Tagline / Slogan',
            'name'  => 'company_tagline',
            'type'  => 'text',
        ],
        [
            'key'           => 'field_company_logo_light',
            'label'         => 'Logo (Light — for dark backgrounds)',
            'name'          => 'company_logo_light',
            'type'          => 'image',
            'return_format' => 'array',
            'preview_size'  => 'medium',
        ],
        [
            'key'           => 'field_company_logo_dark',
            'label'         => 'Logo (Dark — for light backgrounds)',
            'name'          => 'company_logo_dark',
            'type'          => 'image',
            'return_format' => 'array',
            'preview_size'  => 'medium',
        ],
        [
            'key'           => 'field_company_favicon',
            'label'         => 'Favicon / App Icon',
            'name'          => 'company_favicon',
            'type'          => 'image',
            'return_format' => 'array',
            'preview_size'  => 'thumbnail',
            'instructions'  => 'Upload a square PNG/JPG at least 512x512px. The theme will output favicon, Apple touch, Android, and tile icon tags from it.',
        ],
        [
            'key'   => 'field_company_address',
            'label' => 'Address',
            'name'  => 'company_address',
            'type'  => 'textarea',
            'rows'  => 3,
        ],
        [
            'key'           => 'field_company_map_link',
            'label'         => 'Map Link',
            'name'          => 'company_map_link',
            'type'          => 'link',
            'return_format' => 'array',
            'instructions'  => 'Add the Google Maps link for the footer address.',
        ],
        [
            'key'         => 'field_company_phone',
            'label'       => 'Phone Number',
            'name'        => 'company_phone',
            'type'        => 'text',
            'placeholder' => '+383 48 400 096',
        ],
        [
            'key'         => 'field_company_email',
            'label'       => 'Email Address',
            'name'        => 'company_email',
            'type'        => 'email',
            'placeholder' => 'info@emsaks.com',
        ],
    ],
    'location' => [[['param' => 'options_page', 'operator' => '==', 'value' => 'theme-company']]],
]);
