<?php

acf_add_local_field_group([
    'key'                   => 'group_contact_page',
    'title'                 => 'Contact page',
    'fields'                => [
        [
            'key'           => 'field_contact_form_title',
            'label'         => 'Form title',
            'name'          => 'contact_form_title',
            'type'          => 'text',
            'default_value' => 'Na kontaktoni',
            'wrapper'       => ['width' => '50'],
        ],
        [
            'key'           => 'field_contact_form_intro',
            'label'         => 'Form intro text',
            'name'          => 'contact_form_intro',
            'type'          => 'textarea',
            'rows'          => 3,
            'default_value' => 'Për çdo informacion shtesë, jemi në dispozicion përmes formularit online.',
            'wrapper'       => ['width' => '50'],
        ],
        [
            'key'           => 'field_contact_form_post',
            'label'         => 'Contact Form 7 form',
            'name'          => 'contact_form_post',
            'type'          => 'post_object',
            'post_type'     => ['wpcf7_contact_form'],
            'return_format' => 'id',
            'ui'            => 1,
            'instructions'  => 'Select the CF7 form if you want to manage it from the dropdown.',
            'wrapper'       => ['width' => '50'],
        ],
        [
            'key'           => 'field_contact_map_address',
            'label'         => 'Shop Google Maps address',
            'name'          => 'contact_map_address',
            'type'          => 'text',
            'instructions'  => 'The current map address is kept as the shop location.',
            'wrapper'       => ['width' => '70'],
        ],
        [
            'key'           => 'field_contact_shop_map_title',
            'label'         => 'Shop map title',
            'name'          => 'contact_shop_map_title',
            'type'          => 'text',
            'default_value' => 'Dyqani',
            'wrapper'       => ['width' => '30'],
        ],
        [
            'key'           => 'field_contact_depot_map_address',
            'label'         => 'Depot Google Maps address',
            'name'          => 'contact_depot_map_address',
            'type'          => 'text',
            'instructions'  => 'Enter the depot address to generate its embedded map.',
            'wrapper'       => ['width' => '70'],
        ],
        [
            'key'           => 'field_contact_depot_map_title',
            'label'         => 'Depot map title',
            'name'          => 'contact_depot_map_title',
            'type'          => 'text',
            'default_value' => 'Depoja',
            'wrapper'       => ['width' => '30'],
        ],
        [
            'key'           => 'field_contact_blog_enabled',
            'label'         => 'Show blog section',
            'name'          => 'contact_blog_enabled',
            'type'          => 'true_false',
            'ui'            => 1,
            'default_value' => 1,
            'wrapper'       => ['width' => '25'],
        ],
        [
            'key'           => 'field_contact_blog_title',
            'label'         => 'Blog section title',
            'name'          => 'contact_blog_title',
            'type'          => 'text',
            'default_value' => 'Këshilla dhe lajme nga EMSA',
            'wrapper'       => ['width' => '35'],
        ],
        [
            'key'           => 'field_contact_blog_source',
            'label'         => 'Blog posts source',
            'name'          => 'contact_blog_source',
            'type'          => 'select',
            'choices'       => [
                'latest' => 'Latest posts',
                'manual' => 'Select posts manually',
            ],
            'default_value' => 'latest',
            'ui'            => 1,
            'wrapper'       => ['width' => '40'],
        ],
        [
            'key'               => 'field_contact_blog_posts',
            'label'             => 'Blog posts',
            'name'              => 'contact_blog_posts',
            'type'              => 'relationship',
            'post_type'         => ['post'],
            'filters'           => ['search', 'taxonomy'],
            'elements'          => ['featured_image'],
            'min'               => 0,
            'max'               => 8,
            'return_format'     => 'id',
            'conditional_logic' => [[
                [
                    'field'    => 'field_contact_blog_source',
                    'operator' => '==',
                    'value'    => 'manual',
                ],
            ]],
        ],
    ],
    'location'              => [[
        [
            'param'    => 'page_template',
            'operator' => '==',
            'value'    => 'template-contact.php',
        ],
    ]],
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
]);
