<?php

acf_add_local_field_group([
    'key'                   => 'group_global_options',
    'title'                 => 'Templates',
    'fields'                => [
        [
            'key'       => 'field_global_tab_benefits',
            'label'     => 'Benefits Section',
            'name'      => '',
            'type'      => 'tab',
            'placement' => 'top',
        ],
        [
            'key'           => 'field_benefits_shortcode_info',
            'label'         => 'How to print this section',
            'name'          => '',
            'type'          => 'message',
            'message'       => '<strong>Shortcode:</strong> <code>[emsaks_benefits]</code><br><strong>PHP:</strong> <code>echo do_shortcode(\'[emsaks_benefits]\');</code>',
            'new_lines'     => 'wpautop',
            'esc_html'      => 0,
        ],
        [
            'key'           => 'field_benefits_enabled',
            'label'         => 'Show benefits section',
            'name'          => 'benefits_enabled',
            'type'          => 'true_false',
            'ui'            => 1,
            'default_value' => 1,
            'instructions'  => 'Use the shortcode above to show this section on any page.',
        ],
        [
            'key'           => 'field_benefits_background',
            'label'         => 'Background color',
            'name'          => 'benefits_background',
            'type'          => 'color_picker',
            'default_value' => '#d7ebf6',
            'wrapper'       => ['width' => '33'],
        ],
        [
            'key'           => 'field_benefits_icon_color',
            'label'         => 'Icon color',
            'name'          => 'benefits_icon_color',
            'type'          => 'color_picker',
            'default_value' => '#165783',
            'wrapper'       => ['width' => '33'],
        ],
        [
            'key'           => 'field_benefits_text_color',
            'label'         => 'Text color',
            'name'          => 'benefits_text_color',
            'type'          => 'color_picker',
            'default_value' => '#2c2c2c',
            'wrapper'       => ['width' => '33'],
        ],
        [
            'key'          => 'field_benefits_items',
            'label'        => 'Benefits',
            'name'         => 'benefits_items',
            'type'         => 'repeater',
            'layout'       => 'block',
            'button_label' => 'Add benefit',
            'collapsed'    => 'field_benefits_item_title',
            'sub_fields'   => [
                [
                    'key'            => 'field_benefits_item_image',
                    'label'          => 'Image / icon upload',
                    'name'           => 'image',
                    'type'           => 'image',
                    'return_format'  => 'array',
                    'preview_size'   => 'thumbnail',
                    'library'        => 'all',
                    'wrapper'        => ['width' => '30'],
                ],
                [
                    'key'     => 'field_benefits_item_title',
                    'label'   => 'Title',
                    'name'    => 'title',
                    'type'    => 'text',
                    'wrapper' => ['width' => '30'],
                ],
                [
                    'key'     => 'field_benefits_item_text',
                    'label'   => 'Text',
                    'name'    => 'text',
                    'type'    => 'textarea',
                    'rows'    => 2,
                    'wrapper' => ['width' => '40'],
                ],
            ],
        ],

        ['key' => 'field_global_tab_brands', 'label' => 'Brands / Partners', 'name' => '', 'type' => 'tab', 'placement' => 'top'],
        [
            'key'           => 'field_brands_shortcode_info',
            'label'         => 'How to print this section',
            'name'          => '',
            'type'          => 'message',
            'message'       => '<strong>Shortcode:</strong> <code>[emsaks_brands]</code><br><strong>PHP:</strong> <code>echo do_shortcode(\'[emsaks_brands]\');</code><br>This section is also automatically shown in the footer.',
            'new_lines'     => 'wpautop',
            'esc_html'      => 0,
        ],
        [
            'key'           => 'field_brands_enabled',
            'label'         => 'Show brands section',
            'name'          => 'brands_enabled',
            'type'          => 'true_false',
            'ui'            => 1,
            'default_value' => 1,
            'wrapper'       => ['width' => '25'],
        ],
        [
            'key'           => 'field_brands_title',
            'label'         => 'Section title',
            'name'          => 'brands_title',
            'type'          => 'text',
            'default_value' => 'Partnerët tanë',
            'placeholder'   => 'Partnerët tanë',
            'wrapper'       => ['width' => '75'],
        ],
        [
            'key'          => 'field_brands_logos',
            'label'        => 'Partner logos',
            'name'         => 'brands_logos',
            'type'         => 'repeater',
            'layout'       => 'table',
            'button_label' => 'Add partner',
            'collapsed'    => 'field_brands_logo_image',
            'sub_fields'   => [
                [
                    'key'           => 'field_brands_logo_image',
                    'label'         => 'Logo',
                    'name'          => 'logo',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'thumbnail',
                    'library'       => 'all',
                    'wrapper'       => ['width' => '60'],
                ],
                [
                    'key'         => 'field_brands_logo_url',
                    'label'       => 'Link URL (optional)',
                    'name'        => 'url',
                    'type'        => 'url',
                    'wrapper'     => ['width' => '40'],
                ],
            ],
        ],
    ],
    'location'              => [[['param' => 'options_page', 'operator' => '==', 'value' => 'theme-templates']]],
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
]);
