<?php

acf_add_local_field_group([
    'key'                   => 'group_6a1156ab97835',
    'title'                 => 'Home page',
    'fields'                => [

        ['key' => 'field_home_tab_slider',     'label' => 'Slider',               'name' => '', 'type' => 'tab', 'placement' => 'top'],
        [
            'key'          => 'field_home_slider',
            'label'        => 'Slider',
            'name'         => 'home_slider',
            'type'         => 'repeater',
            'layout'       => 'block',
            'button_label' => 'Add slide',
            'collapsed'    => 'field_home_slider_title',
            'sub_fields'   => [
                [
                    'key'     => 'field_home_slider_title',
                    'label'   => 'Title',
                    'name'    => 'title',
                    'type'    => 'text',
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key'     => 'field_home_slider_short_description',
                    'label'   => 'Short description',
                    'name'    => 'short_description',
                    'type'    => 'textarea',
                    'rows'    => 3,
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key'     => 'field_home_slider_button_text',
                    'label'   => 'Button text',
                    'name'    => 'button_text',
                    'type'    => 'text',
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key'     => 'field_home_slider_button_url',
                    'label'   => 'Button URL',
                    'name'    => 'button_url',
                    'type'    => 'url',
                    'wrapper' => ['width' => '50'],
                ],
                [
                    'key'           => 'field_home_slider_image',
                    'label'         => 'Image',
                    'name'          => 'image',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                    'library'       => 'all',
                ],
            ],
        ],

        ['key' => 'field_home_tab_recommended', 'label' => 'Recommended products', 'name' => '', 'type' => 'tab', 'placement' => 'top'],
        [
            'key'           => 'field_home_recommended_enabled',
            'label'         => 'Show recommended products',
            'name'          => 'home_recommended_enabled',
            'type'          => 'true_false',
            'ui'            => 1,
            'default_value' => 1,
            'wrapper'       => ['width' => '25'],
        ],
        [
            'key'           => 'field_home_recommended_title',
            'label'         => 'Recommended products title',
            'name'          => 'home_recommended_title',
            'type'          => 'text',
            'default_value' => 'Të rekomanduara',
            'wrapper'       => ['width' => '35'],
        ],
        [
            'key'           => 'field_home_recommended_source',
            'label'         => 'Recommended products source',
            'name'          => 'home_recommended_source',
            'type'          => 'select',
            'choices'       => [
                'featured' => 'WooCommerce featured products',
                'manual'   => 'Select products manually',
            ],
            'default_value' => 'featured',
            'ui'            => 1,
            'wrapper'       => ['width' => '40'],
        ],
        [
            'key'               => 'field_home_recommended_products',
            'label'             => 'Recommended products',
            'name'              => 'home_recommended_products',
            'type'              => 'relationship',
            'post_type'         => ['product'],
            'taxonomy'          => '',
            'filters'           => ['search'],
            'elements'          => ['featured_image'],
            'min'               => 0,
            'max'               => 12,
            'return_format'     => 'id',
            'conditional_logic' => [[
                [
                    'field'    => 'field_home_recommended_source',
                    'operator' => '==',
                    'value'    => 'manual',
                ],
            ]],
        ],

        ['key' => 'field_home_tab_special',     'label' => 'Special offers',       'name' => '', 'type' => 'tab', 'placement' => 'top'],
        [
            'key'           => 'field_home_special_offers_enabled',
            'label'         => 'Show special offers',
            'name'          => 'home_special_offers_enabled',
            'type'          => 'true_false',
            'ui'            => 1,
            'default_value' => 1,
            'wrapper'       => ['width' => '30'],
        ],
        [
            'key'           => 'field_home_special_offers_title',
            'label'         => 'Special offers title',
            'name'          => 'home_special_offers_title',
            'type'          => 'text',
            'default_value' => 'Oferta speciale',
            'wrapper'       => ['width' => '30'],
        ],
        [
            'key'           => 'field_home_special_offers_products',
            'label'         => 'Special offer products',
            'name'          => 'home_special_offers_products',
            'type'          => 'relationship',
            'post_type'     => ['product'],
            'taxonomy'      => '',
            'filters'       => ['search'],
            'elements'      => ['featured_image'],
            'min'           => 0,
            'max'           => 12,
            'return_format' => 'id',
            'wrapper'       => ['width' => '40'],
        ],

        ['key' => 'field_home_tab_cards',       'label' => 'Image cards',           'name' => '', 'type' => 'tab', 'placement' => 'top'],
        [
            'key'        => 'field_home_card_1',
            'label'      => 'Image card 1 — Large (left)',
            'name'       => 'home_card_1',
            'type'       => 'group',
            'layout'     => 'block',
            'sub_fields' => [
                [
                    'key'     => 'field_home_card1_title',
                    'label'   => 'Title',
                    'name'    => 'title',
                    'type'    => 'text',
                    'wrapper' => ['width' => '33'],
                ],
                [
                    'key'     => 'field_home_card1_text',
                    'label'   => 'Description',
                    'name'    => 'text',
                    'type'    => 'textarea',
                    'rows'    => 2,
                    'wrapper' => ['width' => '34'],
                ],
                [
                    'key'           => 'field_home_card1_image',
                    'label'         => 'Image',
                    'name'          => 'image',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                    'library'       => 'all',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_home_card1_button',
                    'label'         => 'Button',
                    'name'          => 'button',
                    'type'          => 'link',
                    'return_format' => 'array',
                    'wrapper'       => ['width' => '50'],
                ],
            ],
        ],
        [
            'key'        => 'field_home_card_2',
            'label'      => 'Image card 2 — Small (right)',
            'name'       => 'home_card_2',
            'type'       => 'group',
            'layout'     => 'block',
            'sub_fields' => [
                [
                    'key'     => 'field_home_card2_title',
                    'label'   => 'Title',
                    'name'    => 'title',
                    'type'    => 'text',
                    'wrapper' => ['width' => '33'],
                ],
                [
                    'key'     => 'field_home_card2_text',
                    'label'   => 'Description',
                    'name'    => 'text',
                    'type'    => 'textarea',
                    'rows'    => 2,
                    'wrapper' => ['width' => '34'],
                ],
                [
                    'key'           => 'field_home_card2_image',
                    'label'         => 'Image',
                    'name'          => 'image',
                    'type'          => 'image',
                    'return_format' => 'array',
                    'preview_size'  => 'medium',
                    'library'       => 'all',
                    'wrapper'       => ['width' => '50'],
                ],
                [
                    'key'           => 'field_home_card2_button',
                    'label'         => 'Button',
                    'name'          => 'button',
                    'type'          => 'link',
                    'return_format' => 'array',
                    'wrapper'       => ['width' => '50'],
                ],
            ],
        ],

        ['key' => 'field_home_tab_blog',         'label' => 'Blog',                 'name' => '', 'type' => 'tab', 'placement' => 'top'],
        [
            'key'           => 'field_home_blog_enabled',
            'label'         => 'Show blog section',
            'name'          => 'home_blog_enabled',
            'type'          => 'true_false',
            'ui'            => 1,
            'default_value' => 1,
            'wrapper'       => ['width' => '25'],
        ],
        [
            'key'           => 'field_home_blog_title',
            'label'         => 'Blog section title',
            'name'          => 'home_blog_title',
            'type'          => 'text',
            'default_value' => 'Këshilla dhe lajme nga EMSA',
            'wrapper'       => ['width' => '35'],
        ],
        [
            'key'           => 'field_home_blog_source',
            'label'         => 'Blog posts source',
            'name'          => 'home_blog_source',
            'type'          => 'select',
            'choices'       => [
                'latest' => 'Latest posts',
                'manual' => 'Select posts manually',
            ],
            'default_value' => 'latest',
            'ui'            => 1,
            'wrapper'       => ['width' => '40'],
        ],
        [
            'key'               => 'field_home_blog_posts',
            'label'             => 'Blog posts',
            'name'              => 'home_blog_posts',
            'type'              => 'relationship',
            'post_type'         => ['post'],
            'taxonomy'          => '',
            'filters'           => ['search', 'taxonomy'],
            'elements'          => ['featured_image'],
            'min'               => 0,
            'max'               => 8,
            'return_format'     => 'id',
            'conditional_logic' => [[
                [
                    'field'    => 'field_home_blog_source',
                    'operator' => '==',
                    'value'    => 'manual',
                ],
            ]],
        ],

    ],
    'location'              => [[
        [
            'param'    => 'page_template',
            'operator' => '==',
            'value'    => 'template-home.php',
        ],
    ]],
    'menu_order'            => 0,
    'position'              => 'normal',
    'style'                 => 'default',
    'label_placement'       => 'top',
    'instruction_placement' => 'label',
    'active'                => true,
]);
